### ISSUE TITLE
Term request: potassium  in soil package

### ISSUE THREAD

**Issue by StantonMartin** [GenomicsStandardsConsortium/mixs#100]
Should be identical to existing term in sediment package

**New term details**
For us to assess a new term request we require the following details:
```
Term name - 
Structured comment name - [a less than 20char no spaces version of the name]
Definition - [a clear and concise description of the term including ]
Expected value - [e.g. text or EFO and/or OBI etc...]
Value syntax - [e.g. {float} {unit}|{termLabel} {[termID]}|{text}|{timestamp} etc...]
Example - [provide and example value]
Preferred unit - [if appropriate]
Package(s) - [list any packages that should include the new term]
```

**Additional context**
Add any other context about the new term here.

**Comment by only1chunts** [comment]
no new term required

**Comment by turbomam** [comment]
```yaml
  potassium:
    is_a: core field
    title: potassium
    description: Concentration of potassium in the sample
    range: quantity value
    multivalued: false
    examples:
    - value: 463 milligram per liter
    comments: []
    aliases:
    - potassium
    annotations:
      expected_value: measurement value
      preferred_unit: milligram per liter, parts per million
      occurrence: '1'
    slot_uri: MIXS:0000430
```
