### ISSUE TITLE
review Make file for generating mixs.yaml in this new home

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#338]
- [x] unify logging
- [x] how long does this take? maybe tee the logs?
- [x] LinkML gen-project artifacts go in `generated/`, not `.`
  - `release/` is for a stable set of generate artifacts? maybe we shouldn't commit `generated/`?
- [x] poetry?
- [x] md docs generation and conversion to html
- [ ] docs publishing
  - [ ] integration with https://genomicsstandardsconsortium.github.io/gensc.github.io/ aka https://github.com/GenomicsStandardsConsortium/gensc.github.io but probably not https://gensc.org/mixs/
  - [ ] dredge up large images from https://gensc.org/mixs/ or linked papers?
  - [ ] expected docs search experience: querying for a term like depth should bring up a single hit, not one for each checklist X environmental package class as modeled in LinkML
  - [ ] search should be fast. see @only1chunts search at XXX
- [ ] tests
  - what framework?
  - how to invoke?
- [ ] publish package to PyPI
  - what to include? `generated/mixs.py`, `model/schema`?
  - whose account?
  - what credentials?
  - what license? `./LICENSE` says CC0

**Comment by turbomam** [comment]
less directly related to Makefile:
- create a best practices doc or use somebody else's
- where should legacy artifacts go
- make good use of GH releases/tags and branches and make less use of catch all directories in the live main branch
- always document internal and external requirements 
- always document changes
- testing and GH actions
-

**Comment by turbomam** [comment]
Proposed `pyproject.toml`

```toml
[tool.poetry]
name = "mixs-linkml"
version = "0.1.0"
description = "A LinkML (https://linkml.io/) model of the MIxS standard (https://gensc.org/mixs/)"
authors = ["GSC"]
license = "CC0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by turbomam** [comment]
## review dependencies

```toml
[tool.poetry.dependencies]
python = "^3.9"
linkml = ">=1.1.13"
pandas = "*"
mkdocs = "*"

[tool.poetry.dev-dependencies]
pipenv-to-requirements = "*"
tox = "*"
tox-pipenv = "*"
unittest2 = "*"
nbconvert = "*"
nbformat = "*"
ipykernel = "*"
```
