### ISSUE TITLE
bad 'air particulate matter concentration' in addition to valid 'air_PM_concen'

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#397]
'air particulate matter concentration' is the title for slot  `air_PM_concen`

unfortunately, somehow a slot with **name** `air particulate matter concentration` was also created

I think spaces are illegal in LinkML slot names. It's also a lot longer than 20 characters.

**Comment by lschriml** [comment]
Hello Mark,
 email Ramona, Chris and I if there is an urgent issue. 
    There is no character limit for labels, only for structured comment names

Cheers,
Lynn

**Comment by only1chunts** [comment]
Similar to the issue in #394 this is a problem created by mistake at some point by swapping the short name and label in one of the packages.
## Proposal
MIXSID:0000108 in the "air" package should be corrected to use the same details as the "food-farm environment" package

**Comment by only1chunts** [comment]
The correct details for MIXS:0000108 are:
```
name: air_PM_concen
annotations:
  Expected_value:
    tag: Expected_value
    value: particulate matter name;measurement value
description: Concentration of substances that remain suspended in the air, and comprise
  mixtures of organic and inorganic substances (PM10 and PM2.5); can report multiple
  PM's by entering numeric values preceded by name of PM
title: air particulate matter concentration
examples:
- value: PM2.5;10 microgram per cubic meter
from_schema: https://w3id.org/mixs
keywords:
- air
- concentration
- particle
- particulate
string_serialization: '{text};{float} {unit}'
slot_uri: MIXS:0000108
multivalued: true
alias: air_PM_concen
domain_of:
- Air
- FoodFarmEnvironment
range: string
```
The above details are correct in the current main branch. Therefore I am closing this ticket as done.
