### ISSUE TITLE
Normalize inconsistencies in term MIXS:0000002

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#441]
see also #438

```yaml
Definition:
  agriculture: The device used to collect an environmental sample. This field accepts
    terms listed under environmental sampling device (http://purl.obolibrary.org/obo/ENVO).
    This field also accepts terms listed under specimen collection device (http://purl.obolibrary.org/obo/GENEPIO_0002094).
  food-animal and animal feed: The device used to collect an environmental sample.
    This field accepts terms listed under environmental sampling device (http://purl.obolibrary.org/obo/ENVO).
    This field also accepts terms listed under specimen collection device (http://purl.obolibrary.org/obo/GENEPIO_0002094).
  food-farm environment: The device used to collect an environmental sample. This
    field accepts terms listed under environmental sampling device (http://purl.obolibrary.org/obo/ENVO).
    This field also accepts terms listed under specimen collection device (http://purl.obolibrary.org/obo/GENEPIO_0002094).
  food-food production facility: The device employed for collecting the sample.
  food-human foods: The device used to collect an environmental sample. This field
    accepts terms listed under environmental sampling device (http://purl.obolibrary.org/obo/ENVO).
    This field also accepts terms listed under specimen collection device (http://purl.obolibrary.org/obo/GENEPIO_0002094).
Package item:
  agriculture: sample collection device or method
  food-animal and animal feed: sample collection device
  food-farm environment: sample collection device
  food-food production facility: sample collection device
  food-human foods: sample collection device
Value syntax:
  agriculture: '{text}'
  food-animal and animal feed: '{termLabel} {[termID]}|{text}'
  food-farm environment: '{termLabel} {[termID]}|{text}'
  food-food production facility: '{text}'
  food-human foods: '{termLabel} {[termID]}|{text}'
```

The only match for "sample collection device" at https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/ is

Name | Harmonized name | Synonyms | Description | Format
-- | -- | -- | -- | --
sample collection device or method | samp_collect_device | samp collect device,sampling device | Method or device employed for collecting sample | {text}

I propose that 
- all of the `Package item`s be normalized to 'sample collection device or method'
- all of the `Value syntax`es be normalized to '{text}'

I'm less certain about how we should handle the `Definition`s

If we switch to using schemasheets #439, then some of the variations in the `Definition`s (which LinkML models as `description`s) could be put into `comments`, `notes` or `todos` (at the risk of the template getting wider).
