### ISSUE TITLE
Normalize MIXS:0000018 (non-Definition examples)

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#442]
See also #438 

Ignoring variations in the `Definition`:

```yaml
Occurrence:
  agriculture: ''
  food-farm environment: '1'
  host-associated: '1'
  microbial mat/biofilm: '1'
  miscellaneous natural or artificial environment: '1'
  plant-associated: '1'
  sediment: '1'
  soil: '1'
  symbiont-associated: '1'
  wastewater/sludge: '1'
  water: '1'
Package item:
  agriculture: soil depth
  food-farm environment: depth
  host-associated: depth
  microbial mat/biofilm: depth
  miscellaneous natural or artificial environment: depth
  plant-associated: depth
  sediment: depth
  soil: depth
  symbiont-associated: depth
  wastewater/sludge: depth
  water: depth
Structured comment name:
  agriculture: soil_depth
  food-farm environment: depth
  host-associated: depth
  microbial mat/biofilm: depth
  miscellaneous natural or artificial environment: depth
  plant-associated: depth
  sediment: depth
  soil: depth
  symbiont-associated: depth
  wastewater/sludge: depth
  water: depth
```

From https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/

See typo "respectivly" in `Description` 

Name | Harmonized name | Synonyms | Description | Format
-- | -- | -- | -- | --
depth | depth |   | Depth is defined as the vertical distance below surface, e.g. for sediment or soil samples depth is measured from sediment or soil surface, respectivly. Depth can be reported as an interval for subsurface samples. | {float} m

Action: updating `Package item` and `Structured comment name` at [NMDC copy of MIxS 6 term updates](https://docs.google.com/spreadsheets/d/1-ocpwjx6nkBod6aj4kcYeSB5NRlhXaYCcuk3ooX2OV4)
