### ISSUE TITLE
Fix recommended ontologies for sampling device

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs#542]
**Describe the bug**

The description on sample collection device points to ENVO, but ENVO is scoped for environments themselves, rather than equipment.

The actual text also suggests that the URL will take users to a specific term, which isn't the case .

```
samp_collec_device: 
  name: samp_collec_device 
  annotations: 
    expected_value: 
      tag: expected_value 
      value: device name 
  description: The device used to collect an environmental sample. This field accepts terms listed under environmental sampling device (http://purl.obolibrary.org/obo/ENVO). This field also accepts terms listed under specimen collection device (http://purl.obolibrary.org/obo/GENEPIO_0002094). 
  title: sample collection device 
  examples: - value: swab, biopsy, niskin bottle, push core, drag swab [GENEPIO:0002713] 

```

**Expected behavior**

Update description to point to more appropriately scoped semantic resources. These can and should include things like the NERC vocabularies for devices (which may need a different CURIE style supported).

We should also note that free text is accepted. This is shown in the example list, but not explained in the description.

If needed ,we could think about creating a lightweight OBOesque ontology for environmental equipment in the ENVO org
