### ISSUE TITLE
Are all of these prefix definitions really required?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#633]
I think they only appear in examples, but not all example-appearing prefix are defined 

```yaml
  AGRO:
    prefix_prefix: AGRO
    prefix_reference: http://purl.obolibrary.org/obo/AGRO_
  CHEBI:
    prefix_prefix: CHEBI
    prefix_reference: http://purl.obolibrary.org/obo/CHEBI_
  ENVO:
    prefix_prefix: ENVO
    prefix_reference: http://purl.obolibrary.org/obo/ENVO_
```
