### ISSUE TITLE
restore some 'Expected value' content that was lost in MIxS v6.2.0

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#740]

**Comment by turbomam** [comment]
To what extent do the Expected values need to be reiterated verbatim in one of the SlotDefinition metaslots?

`hysterectomy` has this Expected value: 'hysterectomy status'

After the range/pattern conversion, that Expected value is not present anymore.

```yaml
  hysterectomy:
    description: Specification of whether hysterectomy was performed
    title: hysterectomy
    examples:
      - value: 'no'
    slot_uri: MIXS:0000287
    range: boolean
```
