### ISSUE TITLE
reduce length of short name nose_mouth_teeth_throat_disord [MIXS:0000283]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#743]
**Current term details**
```
Term name -  nose/mouth/teeth/throat disorder
Term ID - MIXS:0000283
Structured comment name - nose_mouth_teeth_throat_disord
Definition - History of nose/mouth/teeth/throat disorders; can include multiple disorders
```

**Suggested update(s)**
```
Term name -  nose/mouth/teeth/throat disorder
Term ID - MIXS:0000283
Structured comment name - nosal_oral_disord
Definition - History of nose/mouth/teeth/throat disorders; can include multiple disorders
```

**Additional context**
FYI - the “nose_mouth_teeth_throat_disord” MIXS:0000283 was supposed to have been fixed as part of #84  by changing it to “nose_oral_disord” but it doesn’t appear to have stuck!

**Comment by turbomam** [comment]
Thanks @only1chunts.  Can you link your source for those term details? It would be nice to look at them in both the native LinkML format and this other format that you prefer.

**Comment by only1chunts** [comment]
I did not intend to give the impression of a "preferred format", the ticket is simply a human readable thing to get the issue recorded and addressed (by other humans :-) ).
The current term details are as shown here https://genomicsstandardsconsortium.github.io/mixs/0000283/
The suggested ones are as shown above, i.e. the source is ticket #84

**Comment by only1chunts** [comment]
FYI the v6 excel spreadsheet from [here](https://github.com/GenomicsStandardsConsortium/mixs/blob/mixs6.1.1/mixs/excel/mixs_v6.xlsx) lists BOTH [MIXS:0000283](https://genomicsstandardsconsortium.github.io/mixs/0000283/) and [MIXS:0000270](https://genomicsstandardsconsortium.github.io/mixs/0000270/) with the short name "nose_throat_disord", I'm not sure how that happened (maybe the spreadsheet was manually created for v6?), but the spreadsheet is definitely wrong.

**Comment by turbomam** [comment]
I trust you or others to change this modelling based on whatever documented or mental recollections you have.

I will say that those `descriptions` are far from ideal. If the `multivalued` attribute is set to `true`, then there's no need to repeat "can include multiple disorders" in the description. And all of the notes about where to find should be captures in `comments`, because they are not descriptive of what a `nose_mouth_teeth_throat_disord` or `nose_throat_disord` is. They're comments on how the values should be selected or fomatted.

Ideally we will capture that with [dynamic enumerations](https://linkml.io/linkml/schemas/enums.html#dynamic-enums) in the future.

**Comment by only1chunts** [comment]
discussed at CIG call.
both terms(IXS:0000270 & IXS:0000283) have been used in NCBI Bio Samples >1000 times. we should explore the usage before mkaing a decision.

**Comment by only1chunts** [comment]
@turbomam has looked at usage of those terms in NCBI biosamples see ticket #760

**Comment by only1chunts** [comment]
(Copied note from #760 added by @lschriml)

As noted in the Feb 13th CIG notes:
(Lynn): review of term usage:

→ Review notes below, I would say that we can merge these two terms.
New definition: History of nose,mouth, teeth, and/or throat disorders: can include multiple disorders.

→ and to add in the information for the source of the terms possible values, where appropriate:
The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org/, lung disease (https://disease-ontology.org/?id=DOID:850), upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974),
(https://disease-ontology.org/?id=DOID:2825), mouth disease (https://disease-ontology.org/?id=DOID:403), tooth disease (https://disease-ontology.org/?id=DOID:1091).

MIXS:0000270 - In the human-associated package:
–Structured Comment (short name): nose_throat_disord
– Package Name (long name):lung/nose-throat disorder
-definition:
History of nose-throat disorders; can include multiple disorders, The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org/, lung disease (https://disease-ontology.org/?id=DOID:850), upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974).

MIXS:0000283 - In the human oral package:

– Structured Comment (short name): nose_throat_disord
– Package Name (long name): nose/mouth/teeth/throat disorder
– definition:
History of nose/mouth/teeth/throat disorders; can include multiple disorders. The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org/, nose disease (https://disease-ontology.org/?id=DOID:2825), mouth disease (https://disease-ontology.org/?id=DOID:403), tooth disease (https://disease-ontology.org/?id=DOID:1091), or upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974).

**Comment by only1chunts** [comment]
From the discussions in CIG calls and the comments above are we proposing :
1 - to deprecate MIXS:0000283
AND
2 - Update MIXS:0000270  to 
```
  nose_throat_disord:
    description: Report any history of nose, mouth, teeth and/or throat disorders in the subject. May include multiple disorders.
    title: nose throat disorder
    keywords:
      - disorder
    slot_uri: MIXS:0000270
    alias: nose_mouth_teeth_throat_disord
    comment:  The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, lung disease (https://disease-ontology.org/?id=DOID:850), upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974)
    multivalued: true
    range: string
```
e.g. add an alias for the deprecated term name, and add the comment to hold the description of what values to add.
