### ISSUE TITLE
write python test for terms that have non-UTF-8 characters in their attributes

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#759]
@Woolly-at-EBI in advance of writing any Python, I have tried a few CLI approaches to find non ASCII/UTF-8 characters in mixs.yaml. But I ahven't found any yet. So maybe I'm doing something wrong.

Could you please remind me what you found and what approach you used?

**Comment by turbomam** [comment]
maybe 
- https://github.com/GenomicsStandardsConsortium/mixs/issues/707

**Comment by turbomam** [comment]
On Nov 8, 2023, you found strange characters in `viscosity`'s `description` like
> "A measure of oil's resistance¬†to gradual deformation by¬†shear stress¬†or¬†tensile stress (e.g. 3.5 cp; 100 ¬∞C)"

Here's the definition of `viscosity in v6.2.0. It looks like I already did some replacement of problematic characters with whitespace, since there's some double whitespace below.


```yaml
viscosity:
    annotations:
      Expected_value: measurement value;measurement value
      Preferred_unit: cP at degree Celsius
    description: A measure of oil's resistance  to gradual deformation by  shear stress  or  tensile
      stress (e.g. 3.5 cp; 100   C)
    title: viscosity
    string_serialization: '{float} {unit};{float} {unit}'
    slot_uri: MIXS:0000126
```

**Comment by turbomam** [comment]
I'll locally add some of those strange characters back into mixs.yaml and search again, to make sure my methods work.

**Comment by turbomam** [comment]
Shoot, were did I get that definition of `viscosity` above?!

Maybe by expanding the [linkml-source section of it's documentation page](https://genomicsstandardsconsortium.github.io/mixs/0000126/#linkml-source) on the web?

Here it is, copied straight from `src/mixs/schema/mixs.yaml` in this branch (`759-write-python-test-for-terms-that-have-non-utf-8-characters-in-their-attributes`)

```yaml
  viscosity:
    annotations:
      Expected_value: measurement value;measurement value
      Preferred_unit: cP at degree Celsius
    description: A measure of oil's resistance¬†to gradual deformation by¬†shear stress¬†or¬†tensile stress (e.g. 3.5 cp; 100 ¬∞C)
    title: viscosity
    string_serialization: '{float} {unit};{float} {unit}'
    slot_uri: MIXS:0000126
```
