### ISSUE TITLE
create dendrogram of MIxS extensions, or some other all-vs-all distance metrics

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#766]
https://github.com/GenomicsStandardsConsortium/mixs/blob/766-create-dendrogram-of-mixs-extensions-or-some-other-all-vs-all-distance-metrics/extensions-dendrogram.pdf

![extensions-dendrogram](https://github.com/GenomicsStandardsConsortium/mixs/assets/25185273/5e21ba19-8c7a-4392-8525-77635c8f11d2)

**Comment by turbomam** [comment]
```yaml
Soil_only:
  - agrochem_addition
  - al_sat
  - al_sat_meth
  - annual_precpt
  - annual_temp
  - crop_rotation
  - cur_land_use
  - cur_vegetation
  - cur_vegetation_meth
  - drainage_class
  - extreme_event
  - fao_class
  - fire
  - flooding
  - heavy_metals
  - heavy_metals_meth
  - horizon_meth
  - link_addit_analys
  - link_class_info
  - link_climate_info
  - local_class
  - local_class_meth
  - micro_biomass_meth
  - microbial_biomass
  - ph_meth
  - pool_dna_extracts
  - prev_land_use_meth
  - previous_land_use
  - profile_position
  - season_precpt
  - season_temp
  - sieving
  - slope_aspect
  - slope_gradient
  - soil_horizon
  - soil_texture
  - soil_texture_meth
  - soil_type
  - soil_type_meth
  - store_cond
  - tillage
  - tot_nitro_cont_meth
  - tot_nitro_content
  - tot_org_c_meth
  - tot_org_carb
  - water_cont_soil_meth
  - water_content
Water_only:
  - alkalinity
  - alkalinity_method
  - alkyl_diethers
  - aminopept_act
  - ammonium
  - atmospheric_data
  - bac_prod
  - bac_resp
  - bacteria_carb_prod
  - biomass
  - bishomohopanol
  - bromide
  - calcium
  - carb_nitro_ratio
  - chem_administration
  - chloride
  - chlorophyll
  - conduc
  - density
  - diether_lipids
  - diss_carb_dioxide
  - diss_hydrogen
  - diss_inorg_carb
  - diss_inorg_nitro
  - diss_inorg_phosp
  - diss_org_carb
  - diss_org_nitro
  - diss_oxygen
  - down_par
  - fluor
  - glucosidase_act
  - light_intensity
  - magnesium
  - mean_frict_vel
  - mean_peak_frict_vel
  - n_alkanes
  - nitrate
  - nitrite
  - nitro
  - org_carb
  - organism_count
  - oxy_stat_samp
  - part_org_carb
  - part_org_nitro
  - perturbation
  - petroleum_hydrocarb
  - phaeopigments
  - phosphate
  - phosplipid_fatt_acid
  - photon_flux
  - potassium
  - pressure
  - primary_prod
  - redox_potential
  - salinity
  - samp_store_dur
  - samp_store_loc
  - samp_store_temp
  - silicate
  - size_frac_low
  - size_frac_up
  - sodium
  - soluble_react_phosp
  - sulfate
  - sulfide
  - suspend_part_matter
  - tidal_stage
  - tot_depth_water_col
  - tot_diss_nitro
  - tot_inorg_nitro
  - tot_nitro
  - tot_part_carb
  - tot_phosp
  - turbidity
  - water_current
```
