### ISSUE TITLE
Updates to terms 16S recovered [MIXS:0000065] and 16S recovery software [MIXS:0000066]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#801]
Should expand these terms to enable reporting of the recovery of other taxonomic marker genes, not just 16S?

## Current term details of 16S recovered [[MIXS:0000065](https://genomicsstandardsconsortium.github.io/mixs/0000065/)]

```
name: x16s_recover
description: Can a 16S gene be recovered from the submitted SAG or MAG?
title: 16S recovered
examples:
- value: 'yes'
in_subset:
- sequencing
from_schema: https://w3id.org/mixs
keywords:
- recover
slot_uri: MIXS:0000065
alias: x16s_recover
domain_of:
- Mimag
- Misag
range: boolean
```

## Suggested update(s)
The parts that could be updates are listed below, but further input from experts in the area is required to determine the most suitable ways to make the changes.

name:  **what should the new short name be?** tax_mark_gene_recov
description: **Can a specific taxonomic marker gene be recovered from the submitted SAG or MAG?**
title:  **what should the new full name be?** taxonomic marker gene recovery

## Additional context
These terms are bacterial specific. They are utilised in the MISAG and MIMAG packages, previously @rdfinn has suggested those packages need to be more generic to enable inclusion of non-bacterial MAG/SAGs  (see ticket #602 ) . Can we therefore only specify when a 16S gene is recovered from an assembled genome? I think we should expand the term to enable reporting of recovery of other taxonomic marker genes.

**Question:** If this term is used should it be a requirement for the term "target gene" [[MIXS:0000044](https://genomicsstandardsconsortium.github.io/mixs/0000044/)] to also be included? i.e. together this boolean term yes/no and the gene name from the target gene field give sufficient information.

**Question:** If this term is used should it be a requirement for the term MIXS:0000066 to be used as well? (i.e. the software term below)

## Current term details of 16S recovery software [[MIXS:0000066](https://genomicsstandardsconsortium.github.io/mixs/0000066/)]
```
name: x16s_recover_software
description: Tools used for 16S rRNA gene extraction
title: 16S recovery software
examples:
- value: rambl;v2;default parameters
in_subset:
- sequencing
from_schema: https://w3id.org/mixs
keywords:
- recover
- software
slot_uri: MIXS:0000066
alias: x16s_recover_software
domain_of:
- Mimag
- Misag
range: string
pattern: ^([^\s-]{1,2}|[^\s-]+.+[^\s-]+);([^\s-]{1,2}|[^\s-]+.+[^\s-]+);([^\s-]{1,2}|[^\s-]+.+[^\s-]+)$
structured_pattern:
  syntax: ^{software};{version};{parameters}$
  interpolated: true
  partial_match: true
```

## Suggested update(s)
The parts that could be updates are listed below, but further input from experts in the area is required to determine the most suitable ways to make the changes.

name:  **what should the new short name be?**
description: **Tools used for taxonomic marker gene extraction/recovery.**
title:  **what should the new full name be?**
