### ISSUE TITLE
start converting `string_serialization`s to enumerations

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#839]
[string_serialization](https://linkml.io/linkml-model/latest/docs/string_serialization/) isn't actionable like `range` or `pattern`. It's intended as a hint for how a software agent might want to populate these values give some other inputs

I think I have dragged my feet on this task because 
- I was  worried about the genration of OWL URIs for permissible values that contained punctuation (but this is probably under control now)
- I still don't have any plan for expressing hybrids between enumerations and algebraic expressions like the `{timestamp}` suffix for `add_recov_method`

```yaml
  add_recov_method:
    annotations:
      Expected_value: enumeration;timestamp
    description: Additional (i.e. Secondary, tertiary, etc.) recovery methods deployed
      for increase of hydrocarbon recovery from resource and start date for each one
      of them. If "other" is specified, please propose entry in "additional info"
      field
    title: secondary and tertiary recovery methods and start date
    examples:
    - value: Polymer Addition;2018-06-21T14:30Z
    keywords:
    - date
    - method
    - recover
    - secondary
    - start
    string_serialization: '[Water Injection|Dump Flood|Gas Injection|Wag Immiscible
      Injection|Polymer Addition|Surfactant Addition|Not Applicable|other];{timestamp}'
```

I see 267 `string_serialization`s in mixs.yaml at this date

**Comment by turbomam** [comment]
```yaml
  IFSAC_category:
    annotations:
      Expected_value: IFSAC term
    description: 'The IFSAC food categorization scheme has five distinct levels to
      which foods can be assigned, depending upon the type of food. First, foods are
      assigned to one of four food groups (aquatic animals, land animals, plants,
      and other). Food groups include increasingly specific food categories; dairy,
      eggs, meat and poultry, and game are in the land animal food group, and the
      category meat and poultry is further subdivided into more specific categories
      of meat (beef, pork, other meat) and poultry (chicken, turkey, other poultry).
      Finally, foods are differentiated by differences in food processing (such as
      pasteurized fluid dairy products, unpasteurized fluid dairy products, pasteurized
      solid and semi-solid dairy products, and unpasteurized solid and semi-solid
      dairy products. An IFSAC food category chart is available from https://www.cdc.gov/foodsafety/ifsac/projects/food-categorization-scheme.html
      PMID: 28926300'
    title: Interagency Food Safety Analytics Collaboration (IFSAC) category
    examples:
    - value: Plants:Produce:Vegetables:Herbs:Dried Herbs
    keywords:
    - food
    string_serialization: '{text}'
    slot_uri: MIXS:0001179
    multivalued: true
    required: true
```

- remove `string_serialization`
- set `range` explicitly to `string` (don't rely on schema's `default_range`)

**Comment by turbomam** [comment]
Here's an example where the Expected_value annotation and the `string_serialization` taken together do provide some useful guidance. 


```yaml
  assembly_name:
    annotations:
      Expected_value: name and version of assembly
    description: Name/version of the assembly provided by the submitter that is used
      in the genome browsers and in the community
    title: assembly name
    examples:
    - value: HuRef, JCVI_ISG_i3_1.0
    in_subset:
    - sequencing
    string_serialization: '{text} {text}'
    slot_uri: MIXS:0000057
```

**Comment by turbomam** [comment]
```yaml
assembly_qual:
    annotations:
      Expected_value: enumeration
    description: 'The assembly quality category is based on sets of criteria outlined
      for each assembly quality category. For MISAG/MIMAG; Finished: Single, validated,
      contiguous sequence per replicon without gaps or ambiguities with a consensus
      error rate equivalent to Q50 or better. High Quality Draft:Multiple fragments
      where gaps span repetitive regions. Presence of the large subunit (LSU) RNA, small
      subunit (SSU) and the presence of 5.8S rRNA or 5S rRNA depending on whether it is
      a eukaryotic or prokaryotic genome, respectively.
      Medium Quality Draft:Many fragments with little to no
      review of assembly other than reporting of standard assembly statistics. Low
      Quality Draft:Many fragments with little to no review of assembly other than
      reporting of standard assembly statistics. Assembly statistics include, but
      are not limited to total assembly size, number of contigs, contig N50/L50, and
      maximum contig length. For MIUVIG; Finished: Single, validated, contiguous sequence
      per replicon without gaps or ambiguities, with extensive manual review and editing
      to annotate putative gene functions and transcriptional units. High-quality
      draft genome: One or multiple fragments, totaling   90% of the expected genome
      or replicon sequence or predicted complete. Genome fragment(s): One or multiple
      fragments, totalling < 90% of the expected genome or replicon sequence, or for
      which no genome size could be estimated'
    title: assembly quality
    examples:
    - value: High-quality draft genome
    in_subset:
    - sequencing
    keywords:
    - quality
    string_serialization: '[Finished genome|High-quality draft genome|Medium-quality
      draft genome|Low-quality draft genome|Genome fragment(s)]'
    slot_uri: MIXS:0000056
```

**Comment by turbomam** [comment]
```yaml
  compl_score:
    annotations:
      Expected_value: quality;percent completeness
    description: 'Completeness score is typically based on either the fraction of
      markers found as compared to a database or the percent of a genome found as
      compared to a closely related reference genome. High Quality Draft: >90%, Medium
      Quality Draft: >50%, and Low Quality Draft: < 50% should have the indicated
      completeness scores'
    title: completeness score
    examples:
      - value: med;60%
    in_subset:
      - sequencing
    keywords:
      - score
    string_serialization: '[high|med|low];{percentage}'
    slot_uri: MIXS:0000069
```

**Comment by turbomam** [comment]
```yaml
  contam_screen_param:
    annotations:
      Expected_value: enumeration;value or name
    description: Specific parameters used in the decontamination sofware, such as
      reference database, coverage, and kmers. Combinations of these parameters may
      also be used, i.e. kmer and coverage, or reference database and kmer
    title: contamination screening parameters
    examples:
      - value: kmer
    in_subset:
      - sequencing
    keywords:
      - parameter
    string_serialization: '[ref db|kmer|coverage|combination];{text|integer}'
    slot_uri: MIXS:0000073
```

**Comment by turbomam** [comment]
```yaml
  contam_screen_param:
    annotations:
      Expected_value: enumeration;value or name
    description: Specific parameters used in the decontamination sofware, such as
      reference database, coverage, and kmers. Combinations of these parameters may
      also be used, i.e. kmer and coverage, or reference database and kmer
    title: contamination screening parameters
    examples:
      - value: kmer
    in_subset:
      - sequencing
    keywords:
      - parameter
    string_serialization: '[ref db|kmer|coverage|combination];{text|integer}'
    slot_uri: MIXS:0000073
```
