### ISSUE TITLE
what are our options for diffing schema changes?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#845]
The web interface always says the diff is too large to render

**Comment by mslarae13** [comment]
I've used VS Code. It provides a nice view
https://vscode.one/diff-vscode/

Eric has also provided some useful guidance. We should ask him!

Or, smaller PRs? ;)

**Comment by turbomam** [comment]
- Oct 18, 2023:  v6.2.0
- Oct 9, 2023: mixs6.1.1
- Jul 5, 2022: mixs6.1.0
- Mar 24, 2022: mixs6.0.0
- Feb 27, 2022: MIxS5

**Comment by turbomam** [comment]
get lists of elements like this:

```shell
yq 'keys' mixs_merged_unmaterialized.yaml > mixs_6_0_0_root_keys.tx
```

and

```shell 
yq '.classes | keys' mixs_merged_unmaterialized.yaml > mixs_6_0_0_classes.txt
```

etc.

**Comment by turbomam** [comment]
`settings` were added to the MIxS schema subsequent to version 6.0.0, to build `structured_pattern`s that are reminiscent of the "Value specification" in the MIxS 6 spreadsheet


```yaml
agrochemical_name: ".*"
amount: '[-+]?[0-9]*\.?[0-9]+'
add_recov_methods: 'Water Injection|Dump Flood|Gas Injection|Wag Immiscible Injection|Polymer Addition|Surfactant Addition|Not Applicable|other'
DOI: '^doi:10.\d{2,9}/.*$'
NCBItaxon_id: NCBITaxon:\d+
PMID: ^PMID:\d+$
URL: ^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$
adapter: '[ACGTRKSYMWBHDVN]+'
adapter_A_DNA_sequence: '[ACGTRKSYMWBHDVN]+'
adapter_B_DNA_sequence: '[ACGTRKSYMWBHDVN]+'
ambiguous_nucleotides: '[ACGTRKSYMWBHDVN]+'
boolean: '(?:yes|no)' # a non-capturing group matching either 'yes' or 'no'
country: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
date_time_stamp: '(\d{4})(-(0[1-9]|1[0-2])(-(0[1-9]|[12]\d|3[01])(T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)(\.\d+)?(Z|([+-][01]\d:[0-5]\d))?)?)?)?$'
dna: '^[ACGT]+$'
duration: P(?:(?:\d+D|\d+M(?:\d+D)?|\d+Y(?:\d+M(?:\d+D)?)?)(?:T(?:\d+H(?:\d+M(?:\d+S)?)?|\d+M(?:\d+S)?|\d+S))?|T(?:\d+H(?:\d+M(?:\d+S)?)?|\d+M(?:\d+S)?|\d+S)|\d+W)
float: '[-+]?[0-9]*\.?[0-9]+'
integer: '[1-9][0-9]*'
lat: (-?((?:[0-8]?[0-9](?:\.\d{0,8})?)|90))
lon: -?[0-9]+(?:\.[0-9]{0,8})?$|^-?(1[0-7]{1,2})
name: '.*'
parameters: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
particulate_matter_name: '.*'
region: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
room_name: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
room_number: '[1-9][0-9]*'
scientific_float: '[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?'
software: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
specific_location: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
storage_condition_type: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
termID: '[a-zA-Z]{2,}:[a-zA-Z0-9]\d+'
termLabel: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
text: '.*'
unit: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
version: ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)
```
