### ISSUE TITLE
`heavy_metals` description and guidance is NOT LinkML appropriate

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#860]
https://genomicsstandardsconsortium.github.io/mixs/0000652/

Current:
```
heavy_metals:
    annotations:
      Expected_value: heavy metal name;measurement value unit
      Preferred_unit: microgram per gram
    description: Heavy metals present in the sequenced sample and their concentrations.
      For multiple heavy metals and concentrations, add multiple copies of this field
```
Description's guidance,  "For multiple heavy metals and concentrations, add multiple copies of this field"
You can't do this in LinkML & this guidance won't validation.
Rather, it should be a compound field separated by a `;` or `|` (See https://github.com/GenomicsStandardsConsortium/mixs/issues/465#issuecomment-2256412091)

so ...
```
examples:
    - value: mercury;0.09 micrograms per gram
```
Change to
```
examples:
    - value: mercury,0.09 micrograms per gram
    - value: mercury,0.09 micrograms per gram | lead,0.05 micrograms per gra,
