### ISSUE TITLE
consistently use terse LinkML SimpleDict form whenever possible

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#861]
See Collection Forms in https://linkml.io/linkml-model/latest/docs/specification/06mapping/ 

**One** example is our currently unnecessarily verbose form for prefixes:

```yaml
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  MIXS:
    prefix_prefix: MIXS
    prefix_reference: https://w3id.org/mixs/
```

which could be represented with this `SimpleDict` form:

```yaml
prefixes:
  linkml: https://w3id.org/linkml/
  MIXS:
    prefix_prefix:  https://w3id.org/mixs/
```
