### ISSUE TITLE
never use `name` or `text` metaslots

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#862]
For example, when serialized in YAML, a LinkML schema does not need to declare the `name` or `text` of its entities. In fact, it bloats the files and is a potential source of conflict (relative to the out-dented key that introduces the thing that bears some `name` or `text`)

For example, this:

```yaml
enums:
  AeroStrucEnum:
    name: AeroStrucEnum
    description: permissible values, used by term aero_struc
    from_schema: https://w3id.org/mixs
    permissible_values:
      glider:
        text: glider
      plane:
        text: plane
  AnimalBodyCondEnum:
    name: AnimalBodyCondEnum
    description: permissible values, used by term animal_body_cond
    from_schema: https://w3id.org/mixs
    permissible_values:
      normal:
        text: normal
      over conditioned:
        text: over conditioned
      under conditioned:
        text: under conditioned
```

could be 

```yaml
enums:
  AeroStrucEnum:
    description: permissible values, used by term aero_struc
    from_schema: https://w3id.org/mixs
    permissible_values:
      glider:
      plane:
  AnimalBodyCondEnum:
    description: permissible values, used by term animal_body_cond
    from_schema: https://w3id.org/mixs
    permissible_values:
      normal:
      over conditioned:
      under conditioned:
```
