### ISSUE TITLE
`biocide` and `biocide_admin_method` are inconsistent with other term pairs where one is about the method by which the other was determined

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#879]
Upon further review, there may be two general patterns of "pairs with a method"

```yaml
biocide:
  annotations:
    Expected_value: name;name;timestamp
  description: List of biocides (commercial name of product and supplier) and date of administration
  title: biocide administration
  examples:
    - value: ALPHA 1427;Baker Hughes;2008-01-23
  keywords:
    - administration
  string_serialization: '{text};{text};{timestamp}'
  slot_uri: MIXS:0001011
  recommended: true
biocide_admin_method:
  annotations:
    Expected_value: measurement value;frequency;duration;duration
    Preferred_unit: milligram per liter
  description: Method of biocide administration (dose, frequency, duration, time elapsed between last biociding and sampling) (e.g. 150 mg/l; weekly; 4 hr; 3 days)
  title: biocide administration method
  keywords:
    - administration
    - method
  string_serialization: '{float} {unit};{Rn/start_time/end_time/duration};{duration}'
  slot_uri: MIXS:0000456
  recommended: true
```

vs 

```yaml
cur_vegetation:
  annotations:
    Expected_value: current vegetation type
  description: Vegetation classification from one or more standard classification systems, or agricultural crop
  title: current vegetation
  keywords:
    - vegetation
  range: string
  slot_uri: MIXS:0000312
cur_vegetation_meth:
  description: Reference or method used in vegetation classification
  title: current vegetation method
  keywords:
    - method
    - vegetation
  slot_uri: MIXS:0000314
  range: string
  pattern: ^^PMID:\d+$|^doi:10.\d{2,9}/.*$|^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$$
  structured_pattern:
    syntax: ^{PMID}|{DOI}|{URL}$
    interpolated: true
    partial_match: true
```
