### ISSUE TITLE
 mixs.yaml examples reorganising

### ISSUE THREAD

**Issue by jjkoehorst** [GenomicsStandardsConsortium/mixs#883]
I am working on the ENA / Fair Data Station / MIxS alignment and dived into the rabbit hole of examples. This ticket is more for a work in progress and to create a branch to work on this issue.

for example `host_disease_stat` has multiple examples from different classes. e.g. `rabies [DOID:11260]` `measles [DOID:8622]` but the slot itself has none

```
  host_disease_stat:
    annotations:
      Expected_value: disease name or Disease Ontology term
    description: List of diseases with which the host has been diagnosed; can include
      multiple diagnoses. The value of the field depends on host; for humans the terms
      should be chosen from the DO (Human Disease Ontology) at https://www.disease-ontology.org,
      non-human host diseases are free text
    title: host disease status
    in_subset:
    - nucleic acid sequence source
    keywords:
    - disease
    - host
    - host.
    - status
    string_serialization: '{termLabel} [{termID}]|{text}'
    slot_uri: MIXS:0000031
```

I am working on a script that will add all examples from the classes to the slot and then validates this as well when possible.

Its a work in progress and already thanks @turbomam for the slack conversations.
