### ISSUE TITLE
make `cur_land_use` multivalued

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#905]
https://genomicsstandardsconsortium.github.io/mixs/0001080/

Currently, cur_land_use has a range of 0...1 
meaning not required and not multivalued.

@lschriml was recently working on metadata for the Island Microbiome project and to accurately describe these samples, she wanted to enter multiple value.

Criteria for completion:

- [ ] Evaluate NCBI, do people often provide multiple values? - @turbomam 
- [ ] Decide on the policy for cur_land_use - CIG
- [ ] Submit a PR changing the range. @mslarae13

**Comment by mslarae13** [comment]
@turbomam would you mind getting the NCBI use list together?

**Comment by mslarae13** [comment]
Discuss at CIG AFTER term use is evaluated

**Comment by turbomam** [comment]
cur_land_use | count
-- | --
row crops | 4542
intermixed hardwood and conifers | 3094
vegetable crops | 2108
small grains | 1729
hardwoods (e.g. oak,hickory,elm,aspen) | 1657
agriculture | 1620
not applicable | 995
grass/herbaceous cover | 950
meadows (grasses,alfalfa,fescue,bromegrass,timothy) | 803
35 | 750
conifers (e.g. pine,spruce,fir,cypress) | 734
Agriculture | 703
not collected | 622
farmstead | 548
Grassland | 451
not provided | 451
NA | 401
pastureland (grasslands used for livestock grazing) | 394
forest | 332
mines/quarries | 307
Forest | 269
industrial areas | 269
shrub land (e.g. mesquite,sage-brush,creosote bush,shrub oak,eucalyptus) | 239
agricultural | 239
Crop | 226
abandoned grassland | 222
Cropland | 216
Culture | 215
agricutural experiment | 206
rangeland | 198
marshlands (grass,sedges,rushes) | 178
crop | 175
successional shrub land (tree saplings,hazels,sumacs,chokecherry,shrub dogwoods,blackberries) | 145
hayland | 141
missing | 135
sand | 131
crop cover | 128
Pasture | 126
crops | 102
Vineyard | 88
crop trees (nuts,fruit,christmas trees,nursery trees) | 85
Native | 84
Woodlands | 80
Conifers | 67
horticultural plants (e.g. tulips) | 60
grassland | 56
Crop soil | 53
Arable field | 48
winter reindeer grazing | 48
year-round reindeer grazing | 48
vineyard | 46
tree cover | 45
arable cropland for long-term experimentation | 45
Foret | 44
conventional | 42
natural | 36
agroecological | 36
meadows | 36
Agricultural | 35
mixed boreal forest | 33
winter grazing range of reindeer | 32
summer grazing range of reindeer | 32
vine crops (grapes) | 30
swamp (permanent or semi-permanent water body dominated by woody plants) | 29
pristine | 28
natural high alpine field | 26
Summer grazed by sheep | 21
experimental farm plot | 19
fertilized mown | 18
Forest soil | 18
na | 18
Arable | 17
arable soil | 16
pasture | 16
Woodland | 16
long-term field experiment | 16
Forestal | 15
Deforested | 15
Natura 2000 and National Mire Conservation Programme | 15
fertilized meadow | 15
unfertilized pasture grazed by cattle | 15
soybean cultivation | 13
Bare-fallow | 12
organic fertilization | 12
Continuous arable wheat treatment | 12
Pasture + annual forage crops | 12
Permanent grassland | 12
NaN | 11
shrub crops (blueberries,nursery ornamentals,filberts) | 11
unfertilized | 10
mineral fertilization | 10
cropland | 10
unfertilized grazed | 9
Three long term treatments, bare-fallow, continuous arable wheat treatment and permanent grassland | 9
unmanaged | 9
age class | 9
Forestry with Mixed plantation of Eucalyptus urograndis and Acacia mangium | 8
organic and mineral fertilization | 8
Forestry plantation of Acacia mangium | 8
Forestry with Eucalyptus plantation | 8
dioxin-polluted site | 8
crop land | 7
landfarming, no more dumping | 7
till cropland | 6
cork harvest | 6
National Park | 6
no till cropland | 6
Others | 5
temperate coniferous forest | 4
oil waste areas | 4
Salvage-logging Norway spruce windthrow | 3
Vineyard with conventional treatment. | 3
Mown pasture | 3
unmanged, even-aged, 70-year old Norway spruce forest | 3
unmanaged Norway spruce windthrow | 3
Vineyard with ecophyto treatment. | 3
Manioc cultivation | 3
unmanged, multiple-aged, 190-years old European beech forest | 3
Vineyard with organic treatment. | 3
Close-to-nature managed spruce-beech mixed forest | 3
tropical (e.g. mangrove,palms) | 3
No-till system | 3
Production from Dryland Agriculture and Plantations | 2
temperate woodland | 2
Production from dryland agriculture and plantations | 2
saline seeps | 2
well preserved land use | 2
unmanged, multiple-aged, 120-years old European beech forest | 2
forest clearing | 2
Conventional tillage | 2
Conservation and Natural Environments | 2
Native unfertilized pasture | 2
Meadow | 2
Improved pasture | 2
Secondary forest | 2
Disused asbestos mine, with outcropping fibrous minerals. Recently object of environmental restoration. | 1
In the study area occur typical Arctic soils, mostly gleysols and regosols. | 1
covered by wheat crop | 1
No-till systems | 1
dry/arid uncultivable | 1
use to grow corn | 1
tropical | 1
temperate shrubland | 1
Sample was collected in the area influenced by large breeding colony of planktivorous seabirds, little auks (Alle alle). The colony was situated on Ariekammen mountain slope and consisted of ca. 15,000-20,000 breeding pairs. Sample was collected down the slope, at the colony edge. The vegetation on this well-fertilized area covered ca. 95 % of the surface. | 1
Seconday forest | 1
Outcrop of fibrous tremolite and antigorite (non-asbestos) veins, along the road linking the villages of Chiamberlando, Braida, Bonetti and Riposa. | 1
Auriol disused mine (chrysotile mining in the past, progressively recolonized by local vegetation) and neighbour Ciampanesio site (natural asbestos outcrop). | 1
Not applicable | 1
Outcrop of fibrous tremolite with calcite, in an unused field, along road sides. | 1

**Comment by turbomam** [comment]
```yaml
  cur_land_use:
    annotations:
      Expected_value: enumeration
    description: Present state of sample site
    title: current land use
    examples:
      - value: conifers
    keywords:
      - land
      - use
    string_serialization: '[cities|farmstead|industrial areas|roads/railroads|rock|sand|gravel|mudflats|salt
      flats|badlands|permanent snow or ice|saline seeps|mines/quarries|oil waste areas|small
      grains|row crops|vegetable crops|horticultural plants (e.g. tulips)|marshlands
      (grass,sedges,rushes)|tundra (mosses,lichens)|rangeland|pastureland (grasslands
      used for livestock grazing)|hayland|meadows (grasses,alfalfa,fescue,bromegrass,timothy)|shrub
      land (e.g. mesquite,sage-brush,creosote bush,shrub oak,eucalyptus)|successional
      shrub land (tree saplings,hazels,sumacs,chokecherry,shrub dogwoods,blackberries)|shrub
      crops (blueberries,nursery ornamentals,filberts)|vine crops (grapes)|conifers
      (e.g. pine,spruce,fir,cypress)|hardwoods (e.g. oak,hickory,elm,aspen)|intermixed
      hardwood and conifers|tropical (e.g. mangrove,palms)|rainforest (evergreen forest
      receiving >406 cm annual rainfall)|swamp (permanent or semi-permanent water
      body dominated by woody plants)|crop trees (nuts,fruit,christmas trees,nursery
      trees)]'
    slot_uri: MIXS:0001080
```

**Comment by turbomam** [comment]
NMDC turned that into an enumeration and moved the parenthetical portions into `examples.value`s

```yaml
name: cur_land_use_enum
from_schema: https://w3id.org/nmdc/nmdc
rank: 1000
permissible_values:
  badlands:
    text: badlands
  cities:
    text: cities
  conifers:
    text: conifers
    annotations:
      originally:
        tag: originally
        value: conifers (e.g. pine,spruce,fir,cypress)
    examples:
    - value: cypress
    - value: fir
    - value: pine
    - value: spruce
  crop trees:
    text: crop trees
    annotations:
      originally:
        tag: originally
        value: crop trees (nuts,fruit,christmas trees,nursery trees)
    examples:
    - value: christmas trees
    - value: fruit
    - value: nursery trees
    - value: nuts
  farmstead:
    text: farmstead
  gravel:
    text: gravel
  hardwoods:
    text: hardwoods
    annotations:
      originally:
        tag: originally
        value: hardwoods (e.g. oak,hickory,elm,aspen)
    examples:
    - value: aspen
    - value: elm
    - value: hickory
    - value: oak
  hayland:
    text: hayland
  horticultural plants:
    text: horticultural plants
    annotations:
      originally:
        tag: originally
        value: horticultural plants (e.g. tulips)
    examples:
    - value: tulips
  industrial areas:
    text: industrial areas
  intermixed hardwood and conifers:
    text: intermixed hardwood and conifers
  marshlands:
    text: marshlands
    annotations:
      originally:
        tag: originally
        value: marshlands (grass,sedges,rushes)
    examples:
    - value: grass
    - value: rushes
    - value: sedgees
  meadows:
    text: meadows
    annotations:
      originally:
        tag: originally
        value: meadows (grasses,alfalfa,fescue,bromegrass,timothy)
    examples:
    - value: alfalfa
    - value: bromegrass
    - value: fescue
    - value: grasses
    - value: timothy
  mines/quarries:
    text: mines/quarries
  mudflats:
    text: mudflats
  oil waste areas:
    text: oil waste areas
  pastureland:
    text: pastureland
    annotations:
      originally:
        tag: originally
        value: pastureland (grasslands used for livestock grazing)
    comments:
    - grasslands used for livestock grazing
  permanent snow or ice:
    text: permanent snow or ice
  rainforest:
    text: rainforest
    annotations:
      originally:
        tag: originally
        value: rainforest (evergreen forest receiving greater than 406 cm annual rainfall)
    comments:
    - evergreen forest receiving greater than 406 cm annual rainfall
  rangeland:
    text: rangeland
  roads/railroads:
    text: roads/railroads
  rock:
    text: rock
  row crops:
    text: row crops
  saline seeps:
    text: saline seeps
  salt flats:
    text: salt flats
  sand:
    text: sand
  shrub crops:
    text: shrub crops
    annotations:
      originally:
        tag: originally
        value: shrub crops (blueberries,nursery ornamentals,filberts)
    examples:
    - value: blueberries
    - value: filberts
    - value: nursery ornamentals
  shrub land:
    text: shrub land
    annotations:
      originally:
        tag: originally
        value: shrub land (e.g. mesquite,sage-brush,creosote bush,shrub oak,eucalyptus)
    examples:
    - value: creosote bush
    - value: eucalyptus
    - value: mesquite
    - value: sage-brush
    - value: shrub oak
  small grains:
    text: small grains
  successional shrub land:
    text: successional shrub land
    annotations:
      originally:
        tag: originally
        value: successional shrub land (tree saplings,hazels,sumacs,chokecherry,shrub
          dogwoods,blackberries)
    examples:
    - value: blackberries
    - value: chokecherry
    - value: hazels
    - value: shrub dogwoods
    - value: sumacs
    - value: tree saplings
  swamp:
    text: swamp
    annotations:
      originally:
        tag: originally
        value: swamp (permanent or semi-permanent water body dominated by woody plants)
    comments:
    - permanent or semi-permanent water body dominated by woody plants
  tropical:
    text: tropical
    annotations:
      originally:
        tag: originally
        value: tropical (e.g. mangrove,palms)
    examples:
    - value: mangrove
    - value: palms
  tundra:
    text: tundra
    annotations:
      originally:
        tag: originally
        value: tundra (mosses,lichens)
    examples:
    - value: lichens
    - value: mosses
  vegetable crops:
    text: vegetable crops
  vine crops:
    text: vine crops
    annotations:
      originally:
        tag: originally
        value: vine crops (grapes)
    examples:
    - value: grapes
```
