### ISSUE TITLE
customize owl generator options so that MIxS OWL looks better in Bioportal

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#914]

**Comment by turbomam** [comment]
will this be compatible with the monolithic `gen-project` command?

**Comment by turbomam** [comment]
You can configure the linkml generate project command using:

  1. Command-line arguments:
    - `--include`/`-I`: Specify artifacts to include (e.g., python, jsonschema)
    - `--exclude`/`-X`: Specify artifacts to exclude
    - `--generator-arguments`/`-A`: YAML configuration for specific generators
  2. Configuration file (recommended for complex setups):
    - Create a YAML config file and use `--config-file`/`-C`

  Example config file:

```yaml
  directory: output_dir
  includes:
    - python
    - jsonschema
  excludes:
    - shex
  generator_args:
    jsonschema:
      top_class: Container
    owl:
      metaclasses: false
  mergeimports: true
```

  Command: 

```shell
linkml generate project --config-file config.yaml schema.yaml
```

**Comment by turbomam** [comment]
By default, linkml generate project includes all of these artifact types:

  - graphql
  - jsonldcontext
  - jsonld
  - jsonschema
  - markdown
  - owl
  - prefixmap
  - proto
  - python
  - shex
  - shacl
  - sqltable
  - excel

Technically speaking, none are omitted by default. But I think the inclusion lit above implicitly omits everything else

**Comment by turbomam** [comment]
therefore these are excluded

  - csv
  - doc
  - erdiagram
  - golang
  - golr-views
  - graphviz
  - java
  - namespaces
  - plantuml
  - pydantic
  - rdf
  - sparql
  - sqla
  - sssom
  - summary
  - terminusdb
  - typescript
  - yaml
  - yuml

**Comment by turbomam** [comment]
This is a summary of our current configuration

  1. Main generation commands:
    `- gen-project`: Generates all project files
    `- gen-examples`: Copies example files
    `- gendoc`: Generates documentation
    `- gen-excel`: Generates Excel files
  2. Explicitly included:
    - Line 33: include `project.Makefile`
    - Line 201: include `project.Makefile`
  3. Explicitly excluded:
    - Line 33: `GEN_PARGS` = `--exclude excel --exclude graphql --exclude markdown --exclude prefixmap --exclude protobuf --exclude shacl --exclude shex`
    - Comment line 30: #include config.env (commented out)

**Comment by turbomam** [comment]
```shell
find . -name mixs.py
```

> ./tmp/mixs.py
> ./src/mixs/datamodel/mixs.py

```shell
tree project
```

> ```
> project
> ├── jsonld
> │   ├── mixs.context.jsonld
> │   └── mixs.jsonld
> ├── jsonschema
> │   └── mixs.schema.json
> ├── owl
> │   └── mixs.owl.ttl
> ├── protobuf
> │   └── mixs.proto
> └── sqlschema
>     └── mixs.sql
> ```

**Comment by turbomam** [comment]
```shell
make clean
```

> rm -rf project
> rm -rf tmp
> rm -fr docs/*
> rm -fr src/mixs/datamodel/*

**Comment by turbomam** [comment]
```shell
date && time linkml generate project src/mixs/schema/mixs.yaml && date
```

started at Mon Apr 21 11:46:27 AM EDT 2025

seems like this mode of running the project generator is very quiet by default

**Comment by turbomam** [comment]
we probably want to exclude excel and docs because we have explicit targets and configurations for those

**Comment by turbomam** [comment]
try this configuration

```yaml
  directory: project_2
  includes:
    - csv
    - golang
    - golr-views
    - graphql
    - java
    - jsonld
    - jsonldcontext
    - jsonschema
    - namespaces
    - owl
    - prefixmap
    - proto
    - pydantic
    - python
    - rdf
    - shacl
    - shex
    - sparql
    - sqla
    - sqltable
    - sssom
    - summary
    - terminusdb
    - typescript
  excludes:
    - doc # do separately
    - erdiagram # would be a very large diagram
    - excel # do separately
    - graphviz # would be a very large diagram
    - markdown # redundant with separate documentation
    - plantuml # would be a very large diagram
    - yaml # cannonical-izastion of schema ... do `linkml --format yaml --not-materialize-attributes --materialize-patterns` 
    - yuml # would be a very large diagram
  mergeimports: true
```

**Comment by turbomam** [comment]
## In the YAML configuration file for linkml generate project, you can specify these options:

### For RDF output:

```yaml
  generator_args:
    rdf:
      format: ttl  # Options: ttl, xml, n3, nt, trig, json-ld
      context: "https://context.example.org/my-context.jsonld"  # Or a list of contexts
      emit_metadata: true  # Include schema metadata (default: false)
```

### For OWL output:

```
  generator_args:
    owl:
      format: ttl  # Options: owl, ttl
      metadata_profile: linkml  # Options: linkml, rdfs, ols
      metadata_profiles: []  # List of profiles
      type_objects: false  # Model types as objects instead of literals
      metaclasses: false  # Include LinkML metamodel as metaclasses
      add_root_classes: false  # Add LinkML metamodel classes as superclasses
      add_ols_annotations: true  # Include OLS-specific annotations
      ontology_uri_suffix: ".owl.ttl"  # Suffix for ontology URI
      assert_equivalent_classes: false  # Use owl:equivalentClass vs skos:exactMatch
      use_native_uris: true  # Use definition_uris instead of class_uris
      mixins_as_expressions: false  # Use OWL existential restrictions for mixins
      default_permissible_value_type: "owl:Class"  # Or "owl:NamedIndividual"
      enum_iri_separator: "#"  # Separator used in enum IRIs
```
