### ISSUE TITLE
upgrade to LinkML 1.9.1 when available

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#915]
for exclude linting by type and much more

then what should our default Python version be?

**Comment by turbomam** [comment]
monitor this page. don't use a _release candidate_

- https://github.com/linkml/linkml/releases

**Comment by turbomam** [comment]
we're on 1.8.4 now

**Comment by turbomam** [comment]
specified as 

```toml
[tool.poetry.dependencies]
python = "^3.9"
linkml-runtime = "^1.6.0"
#...

[tool.poetry.group.dev.dependencies]
linkml = "^1.6.0"
```

in `pyproject.toml`
