### ISSUE TITLE
start using type exclusions in linkml linter

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#918]
### before

```shell
linkml lint src/mixs/schema/mixs.yaml | wc -l
```

> 605

**Comment by turbomam** [comment]
add a `.linkmllint.yaml` file

**Comment by turbomam** [comment]
with this kind of a style

```yaml
# Use all the recommended rules and also enable the no_empty_title rule
extends: recommended
rules:
  no_empty_title:
    level: error
```

**Comment by turbomam** [comment]
```yaml
extends: recommended
rules:
  recommended:
    level: error
```

**Comment by turbomam** [comment]
from https://github.com/linkml/linkml/blob/main/linkml/linter/config/datamodel/config.yaml


```yaml
  MetamodelElementTypeEnum:
    description: >-
      The permissible values for the exclude_type slot
    permissible_values:
      class_definition:
        meaning: linkml:ClassDefinition
      enum_definition:
        meaning: linkml:EnumDefinition
      permissible_value:
        meaning: linkml:PermissibleValue
      slot_definition:
        meaning: linkml:SlotDefinition
```

**Comment by turbomam** [comment]
```yaml
extends: recommended
rules:
  recommended:
    level: error
    exclude_type:
      - enum_definition
```

```shell
linkml lint src/mixs/schema/mixs.yaml | wc -l
```

> 475
