### ISSUE TITLE
define "slot_name" also known as "structured_comment_name"

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#926]

**Comment by turbomam** [comment]
All LinkML slots have a name, even if it isn't explicitly asserted. For example, in this minimal schema:

```yaml
id: http://example.com/minimal # range URI
name: minimal
default_prefix: minimal
prefixes:
  minimal: http://example.com/minimal/
slots:
  age:
    required: true
    description: the amount of time since something was created, born,, etc.
```

is inferred to mean this

```yaml
slots:
  age:
    name: age
    description: the amount of time since something was created, born,, etc.
    from_schema: http://example.com/minimal
    required: true
```
