### ISSUE TITLE
list the number of times each LinkML metaslot is used in MIxS term/slot definitions, plus important patterns in which those slots have been populated

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#945]
for @jfy133 , @only1chunts and others

There are so many ways to determine this, but `yq` has been a good choice in general

using

```shell
yq --version
```

> yq (https://github.com/mikefarah/yq/) version v4.44.5

```shell
yq '.slots.* | to_entries | .[].key' mixs.yaml | sort | uniq -c
```

> ```
>       1 aliases
>     401 annotations
>      14 comments
>       2 deprecated
>    1057 description
>     287 domain
>     577 examples
>     287 inlined
>     287 inlined_as_list
>      98 in_subset
>     665 keywords
>     437 multivalued
>     274 pattern
>     882 range
>      55 recommended
>      35 required
>    1059 slot_uri
>     160 string_serialization
>     286 structured_pattern
>    1059 title
> ```

**Comment by turbomam** [comment]
And for slot usages within classes:

```shell
yq '.classes.[].slot_usage.* | to_entries | .[].key' mixs.yaml | sort | uniq -c
```

> ```
>       2 comments
>       6 description
>     228 examples
>     330 recommended
>     124 required
>      44 string_serialization
>       1 structured_pattern
> ```

**Comment by turbomam** [comment]
what annotations are used?

what about pre-materializing the schema?

what slots or class/slot usages have an **asserted** `pattern` and a `structured_pattern`?

what slots or class/slot usages have both `recommended` and `required`?

there are so many ways to determine this, but `yq` has proven fast for the questions above

**Comment by turbomam** [comment]
### what annotations are used on slots?

_No annotations are asserted on slot_usages, as demonstrated by this previous query_

```shell
yq '.classes.[].slot_usage.* | to_entries | .[].key' mixs.yaml | sort | uniq -c
```

```shell
yq '.slots.[].annotations | to_entries | .[].key' mixs.yaml | sort | uniq -c
```

    215 Expected_value
    238 Preferred_unit

**Comment by turbomam** [comment]
### with an asserted `pattern` and a `structured_pattern`

```shell
yq '                                                                                                 
  .classes | to_entries |
  .[] |
  .key as $class |
  (.value.attributes // {} | to_entries |
    map(select(.value.pattern and .value.structured_pattern)) |
    .[] |
    "\($class).\(.key)"
  )
' mixs_attribute_induced.yaml
```

There are a lot!

Double check one

```shell
yq '.classes.MiuvigWater.attributes.water_current | del(.domain_of)' mixs_attribute_induced.yaml
```

```yaml
name: water_current
annotations:
  Preferred_unit:
    tag: Preferred_unit
    value: cubic meter per second, knots
description: Measurement of magnitude and direction of flow within a fluid
title: water current
examples:
  - value: 10 cubic meter per second
from_schema: https://w3id.org/mixs
keywords:
  - water
slot_uri: MIXS:0000203
alias: water_current
owner: MiuvigWater
range: string
pattern: ^[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?( *- *[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)? *([^\s-]{1,2}|[^\s-]+.+[^\s-]+)$
structured_pattern:
  syntax: ^{scientific_float}( *- *{scientific_float})? *{text}$
  interpolated: true
  partial_match: true
```

**Comment by jfy133** [comment]
Is the purpose of this exploration to gauge how much 'clean up' we may need to do @turbomam ?

**Comment by turbomam** [comment]
I wasn't really think of **this issue** in terms of cleanup. I was think more in terms demonstrating which LinkML metaslots we have used, and how contributors can check this stuff for themselves over time without needing to write Python applications that import LinkML for SchemaView.

I guess the fact that there are 1059 slots with a `title` and a `slot_uri` but only 1057 with a `description` could be a call for cleanup!

**Comment by turbomam** [comment]
`yq` syntax can get complicated sometimes, but most LLMs are pretty good at providing guidance in you share examples of what  you've done so far that has worked, and what new incremental feature you want to add

```shell
yq '.slots | to_entries | map(select(.value.description == null)) | from_entries' src/mixs/schema/mixs.yaml
```

```yaml
soil_pH:
  title: soil pH
  examples:
    - value: '7.2'
  keywords:
    - ph
    - soil
  slot_uri: MIXS:0001160
  range: float
water_pH:
  title: water pH
  examples:
    - value: '7.2'
  keywords:
    - ph
    - water
  slot_uri: MIXS:0001175
  range: float
```
