### ISSUE TITLE
document the consequences of the different kinds of materialization

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#947]

**Comment by turbomam** [comment]
```shell
poetry run linkml generate linkml --help
```

> ```
> Usage: linkml generate linkml [OPTIONS] YAMLFILE
> 
> Options:
>   -V, --version                   Show the version and exit.
>   -o, --output PATH               Name of JSON or YAML file to be created
>   --materialize-patterns / --no-materialize-patterns
>                                   Materialize structured patterns as patterns
>                                   [default: materialize-patterns]
>   --materialize-attributes / --no-materialize-attributes
>                                   Materialize induced slots as attributes
>                                   [default: materialize-attributes]
>   --materialize / --no-materialize
>                                   Materialize both, induced slots as
>                                   attributes and structured patterns as
>                                   patterns  [default: materialize]
>   -f, --format [json|yaml]        Output format  [default: json]
>   --metadata / --no-metadata      Include metadata in output  [default:
>                                   metadata]
>   --useuris / --metauris          Use class and slot URIs over model uris
>                                   [default: useuris]
>   -im, --importmap FILENAME       Import mapping file
>   --log_level [CRITICAL|ERROR|WARNING|INFO|DEBUG]
>                                   Logging level  [default: WARNING]
>   -v, --verbose                   Verbosity. Takes precedence over
>                                   --log_level.
>   --mergeimports / --no-mergeimports
>                                   Merge imports into source file
>                                   (default=mergeimports)
>   --stacktrace / --no-stacktrace  Print a stack trace when an error occurs
>                                   [default: no-stacktrace]
>   --help                          Show this message and exit.
> 
> ```

**Comment by turbomam** [comment]
This is slow for MIxS!

```shell
time poetry run linkml generate linkml \
    --output mixs_attribute_induced.yaml \
    --no-materialize-patterns \
    --materialize-attributes \
    --format yaml \
    src/mixs/schema/mixs.yaml 
```

**Comment by turbomam** [comment]
Background:
- MIxS 6.2 was constructed by mining an official GSC MIxS 6 XLSX file with sheets for the checklists and extensions
- global slot definitions were generalized from the way terms were used in those two sheets
- the checklists and extensions were modeled as classes, which declare their use of the global slots and can make minimal `slot_usage` overrides on some metaslot values
- binary combinations of all 11 `Checklist`s and 23 `Extension`s were pre-declared using `mixins` for checklists and `is_a` for environments
    - the combinations are given titles and other textual annotations (in both the informal and strict LinkML sense) but no static structural assertions are made
    - since the mixin nature of classes like `Mims`  must be declared in the schema, that association patterns can't be casually modified
    - a combination can only inherit from one `is_a` parent
    - LinkML has no provision for combining the classes in any other way at runtime, but there's no reason we (or somebody else) can't make application-specific MIxS variants that have different combinations. If the number of combinations is decreased, then the performance of that variant will improve
    - combination classes could also be declared explicitly. That would make it much harder to maintain the schema
    - maybe we should ask LinkML to address things like what metaslot value takes precedent when a class is combined though `is_a` and `mixins`.

```yaml
  MimsSoil:
    name: MimsSoil
    description: MIxS Data that comply with the Mims checklist and the Soil Extension
    title: Mims combined with Soil
    in_subset:
    - combination_classes
    from_schema: https://w3id.org/mixs
    is_a: Soil
    mixins:
    - Mims
```

**Comment by turbomam** [comment]
`--materialize-patterns` turns `structured_pattern`s that use `settings` into regular expression `patterns`

we probably shouldn't have any slots with `structured_pattern`s and asserted `patterns` in the source schema. But we haven't been doing a good job of differentiating a the source schema from a materialized schema that is ready to be applied to data

**Comment by turbomam** [comment]
`--materialize-attributes` generates a schema in which classes have one `attributes` for each slot that is assigned to them or inherited though `is_a` or `mixins`. The behavior of those attributes is a combination of features inherited from the global definition of the slot, `slot_usage` specialization from the class, and possibly features from `slot_usage`s on the parent slots?

_I feel like some of that (whose value wins for each metaslot) needs to be better documented in LinkML_

**Comment by turbomam** [comment]
```shell
time yq '.classes.MimsSoil.attributes.env_broad_scale | del(.domain_of)' mixs_attribute_induced.yaml
```

```yaml
name: env_broad_scale
description: 'Report the major environmental system the sample or specimen came from. The system(s) identified should have a coarse spatial grain, to provide the general environmental context of where the sampling was done (e.g. in the desert or a rainforest). We recommend using subclasses of EnvO s biome class:  http://purl.obolibrary.org/obo/ENVO_00000428. EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS'
title: broad-scale environmental context
examples:
  - value: rangeland biome [ENVO:01000247]
in_subset:
  - environment
from_schema: https://w3id.org/mixs
keywords:
  - context
  - environmental
slot_uri: MIXS:0000012
alias: env_broad_scale
owner: MimsSoil
range: string
required: true
pattern: ^([^\s-]{1,2}|[^\s-]+.+[^\s-]+) \[[a-zA-Z]{2,}:[a-zA-Z0-9]\d+\]$
structured_pattern:
  syntax: ^{termLabel} \[{termID}\]$
  interpolated: true
  partial_match: true
```

> ```
> real	0m9.145s
> user	0m13.406s
> sys	0m1.156s
> ```
