### ISSUE TITLE
specify how the LinkML `multivalued` metaslot should be used with MIxS terms

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#952]

**Comment by turbomam** [comment]
Working backwards, here is the canonical way to represent two MIxS HumanGut records in a YAML data file (which most MIxS users would never do)

human_gut_data:
  - samp_name: sample1
    project_name: project1
    special_diet:
      - low carb
      - vegetarian
  - samp_name: sample2
    project_name: project1
    special_diet:
      - low carb
      - reduced calorie

**Comment by jfy133** [comment]
The result when flattening to a TSV with `linkml convert`

https://github.com/GenomicsStandardsConsortium/mixs/pull/943#discussion_r2085336856

**Comment by turbomam** [comment]
takes a few minutes

**Comment by turbomam** [comment]
samp_name | project_name | special_diet
-- | -- | --
sample1 | project1 | [low carb\|vegetarian]
sample2 | project1 | [low carb\|reduced calorie]

so from a strict LinkML perspective, one could update the special_diet examples in the schema like this

examples:
    - value: '[low carb|vegetarian]'
    - value: '[low carb|reduced calorie]'

**Comment by turbomam** [comment]
Feedback/LinkML news from @cmungall 

Don't lock a single serialization into the examples, especially when LinkML's serialization/de-serialization rules for multiple values in CSV/TSV could change soon

Instead, switch from using the `value` metaslot to the  https://linkml.io/linkml-model/latest/docs/value_object/ metaslot, which can take a list abstraction.

I think that would look like


```yaml
examples:
    - value_object:
        - low carb
        - vegetarian
    - value_object:
        - low carb
        - reduced calorie
```

**Comment by jfy133** [comment]
To clarify, let's say multivalued MIxS slots must have example of both single and multi-value examples it would look like:

```
examples:
   - value
        - low carb 
   - value_object:
        - low carb
        - vegetarian
    - value_object:
        - low carb
        - reduced calorie
```

So first example is a single value (even if multi-valued is a allowed), and the second and third is if you have multiple values for the slots.

I guess the question then is how does this get rendered for a _user_ to know how to fill in that term e.g. when submitting data to the ENA etc?
