### ISSUE TITLE
LinkML linting errors are not exposed in PR

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#961]
I don't see the linting report in the files changed tab

https://github.com/GenomicsStandardsConsortium/mixs/pull/955/files

or in the action log

https://github.com/GenomicsStandardsConsortium/mixs/actions/runs/15121196175/job/42503750122?pr=955

> ```
> Run ## Results file header and basic formatting
>   ## Results file header and basic formatting
>   printf '# LinkML Linting Results \n\n' > linting-results.md
>   printf "$(poetry run linkml --version) linting found the following issues. \n\n" >> linting-results.md
>   printf "_For more information about the linting rule categories, see the [LinkML linter documentation](https://linkml.io/linkml/schemas/linter.html#rules)._\n" >> linting-results.md
>   ## Lint the schema, and further format
>   poetry run linkml lint --ignore-warnings -f markdown src/mixs/schema/mixs.yaml >> linting-results.md
>   shell: /usr/bin/bash -e {0}
> Error: Process completed with exit code 2.
> ```

**Comment by turbomam** [comment]
## ✅ Recommendation

To make the linting results visible, add a step like this to your workflow:

### Option 1: Upload the linting report as an artifact
```yaml
- name: Upload linting report
  uses: actions/upload-artifact@v3
  with:
    name: linting-results
    path: linting-results.md
```

### Option 2: Post it as a PR comment
```yaml
- name: Comment with linting results
  if: failure()
  uses: actions/github-script@v6
  with:
    script: |
      const fs = require('fs');
      const body = fs.readFileSync('linting-results.md', 'utf8');
      github.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: body
      });
```
