### ISSUE TITLE
Term request: calcium  in soil package

### ISSUE THREAD

**Issue by StantonMartin** [GenomicsStandardsConsortium/mixs#99]
should be identical to existing term in misc package

**New term details**
For us to assess a new term request we require the following details:
```
Term name - calcium
Structured comment name - [a less than 20char no spaces version of the name]
Definition - [a clear and concise description of the term including ]
Expected value - [e.g. text or EFO and/or OBI etc...]
Value syntax - [e.g. {float} {unit}|{termLabel} {[termID]}|{text}|{timestamp} etc...]
Example - [provide and example value]
Preferred unit - [if appropriate]
Package(s) - [list any packages that should include the new term]
```

**Additional context**
Add any other context about the new term here.

**Comment by only1chunts** [comment]
Hi @StantonMartin ,
I'm not familiar with what you are trying to achieve so my apologies if I'm missing the point here.
If a term is already included in a package anywhere we do not need to duplicate it, simply reuse it in your package with the same name, same description and same ID number.
If a new term is actually required, please provide more details (as per the template).
Please let me know if this (or any of the other tickets you created for similar requests) can be closed now?
Thanks

**Comment by StantonMartin** [comment]
Hi Chris,
We are trying to describe a soil biosample using the soil MixS package. The terms requested are not in that package, hence the only way to do it is to use a bunch of other packages (like sediment or misc) to describe our elements.. So we end up with a biosample that is described using terms from multiple packages.  Someone mentioned, that this is not best practice, and I noted there are other terms that are duplicated across packages (depth for instance) so I requested the new terms be added to soil.  For some elements like Manganese, they are not in any package, hence the request.   If I am misunderstanding something about how to use MixS let me know.  In the absence of the terms, we can always do what we are doing now which is to mix and match packages in a single biosample and use the misc term for any element that we cannot find in a package.

Thanks,
Stan

**Comment by only1chunts** [comment]
Hi,
Thanks for explaining. The packages are collections of terms that have been compiled by experts in those particular area's as being the set of terms most useful and/or likely to be reported. Each individuals use of a package can vary as much as required for the specific purposes of that sample, so if your samples need terms that are present in the MIxS term list somewhere then by all means use those. 
Sorry its not very clear at the moment, but moving forward we are trying to streamline everything so that its more obvious that the terms can be bundled in any combination as required, with the named environmental-packages simply being a bundle of terms that has been agreed by a community of experts as being appropriate for a particular environment.
The Minimum Information is the same across any environmental package within each of the checklists, although each environmental-package also makes recommendations as to which items are Expected to recorded.
We are in the process of creating a new website with better instructions, but in the mean time, some information that may be useful can be found in the [wiki section](https://github.com/GenomicsStandardsConsortium/mixs/wiki/1.-Background) of this repo.
I will close this ticket and tickets #100 & #101 as they are not required. 
Thanks, Chris.

**Comment by turbomam** [comment]
```yaml
  calcium:
    is_a: core field
    title: calcium
    description: Concentration of calcium in the sample
    range: quantity value
    multivalued: false
    examples:
    - value: 0.2 micromole per liter
    comments: []
    aliases:
    - calcium
    annotations:
      expected_value: measurement value
      preferred_unit: milligram per liter, micromole per liter, parts per million
      occurrence: '1'
    slot_uri: MIXS:0000432
```
